service: test-app

frameworkVersion: "3"

provider:
  name: aws
  runtime: provided.al2
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ca-central-1'}
  environment:
    THUMBNAILS_S3_BUCKET: bentley-auto-thumbnail-${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource: arn:aws:s3:::${self:provider.environment.THUMBNAILS_S3_BUCKET}/*
package:
  individually: true

functions:
  saveDevice:
    handler: bootstrap
    package:
      artifact: build/saveDevice.zip
    events:
      - httpApi:
          path: /save-device
          method: post
  sendSquawk:
    handler: bootstrap
    package:
      artifact: build/sendSquawk.zip
    events:
      - httpApi:
          path: /send-squawk
          method: post
